### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#100]
When I load the previous conferences like 2017 or 2016 and click on Speakers it loads the 2018 speakers. Please check and rectify.

**Comment by prathamesh-sonpatki** [comment]
@anuja-joshi _A

**Comment by anuja-joshi** [comment]
Fixed.

**Note:**
When ever we will move current repo to Past Conferences, we need to make sure we update `_config.yml` as well to add `github_project_name: 'http://rubyconfindia.org/<year>'`, so that all links will point to that year's site.

**Comment by prathamesh-sonpatki** [comment]
Also for moving current repo to past conferences, what we do is - take a backup of rubyconfindia.github.io repo and rename it to next year like 2018 and then push it as new repo on github.
