### ISSUE TITLE
RubyConfIndia Ruby Hero Award page

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#11]
A page should be there on our site for RubyConfIndia Ruby Hero Award - something on these lines - http://rubyheroes.com/

**Comment by IndianGuru** [comment]
Create a page as shown in the attached .pdf

[RubyHero.pdf](https://github.com/rubyconfindia/rubyconfindia.github.io/files/86712/RubyHero.pdf)

**Comment by prashant3863** [comment]
@IndianGuru I just added the ruby hero award page under events tab, please have a look and let me know. thanks

**Comment by IndianGuru** [comment]
Small change - 
Instead of "and announces the winners at [RubyConfIndia](http://rubyconfindia.org/)"
make it -
"and shall announce the winner at [RubyConfIndia](http://rubyconfindia.org/)."

**Comment by IndianGuru** [comment]
"and shall announce the winner at RubyConfIndia."

On site - Missing full stop after RubyConfIndia and winner not winners
