### ISSUE TITLE
set up https for rubyconfindia.org

### ISSUE THREAD

**Issue by coderhs** [rubyconfindia/2019#114]
SInce chrome is going to start all non-https website as un-secure from July, 2018 (https://techcrunch.com/2018/02/08/chrome-will-soon-mark-all-unencrypted-pages-as-not-secure/) we should look into setting up https for custom domain GitHub pages.

I found this solution through Cloudflare, I haven't tried it personally but perhaps we can give it a shot. 

https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by smtalimett** [comment]
We need to do this for all our sites.

**Comment by prathamesh-sonpatki** [comment]
I setup the certificate using netlify: https://www.rubyconfindia.org/ is working but showing errors as URLs are not working correctly.

**Comment by prathamesh-sonpatki** [comment]
@coderhs Check https://www.netlify.com/, very easy to get started. https://www.deccanrubyconf.org/ is migrated and forces SSL now.

**Comment by prathamesh-sonpatki** [comment]
Fixed now.
