### ISSUE TITLE
Links to Past conferences broken

### ISSUE THREAD

**Issue by shaunakpp** [rubyconfindia/2019#117]
I was referencing RubyConfIndia 2017 link somewhere and found out that links to previous conferences are returning 404 not found. 

<img width="1280" alt="screen shot 2018-05-03 at 1 06 51 pm" src="https://user-images.githubusercontent.com/3170078/39564700-e5990dd6-4ed2-11e8-9eaa-000d3fbde31d.png">

**Comment by prathamesh-sonpatki** [comment]
Looks like I broke it when I moved the site to netlfiy. I will fix it in next few days.

**Comment by anildigital** [comment]
ditto

**Comment by shaunakpp** [comment]
Thank you so much for fixing this. 👍🏼
