### ISSUE TITLE
Old site links are broken

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#120]
https://www.rubyconfindia.org/2010/
https://www.rubyconfindia.org/2011/
https://www.rubyconfindia.org/2012/
https://www.rubyconfindia.org/2013/
https://www.rubyconfindia.org/2014/
https://www.rubyconfindia.org/2015/
https://www.rubyconfindia.org/2016/
https://www.rubyconfindia.org/2017/

**Comment by prathamesh-sonpatki** [comment]
We deployed on netlfiy so the github-pages style of rubyconfindia/year no longer works. We setup year.rubyconfindia.org and updated it most of the places. That should work now.

**Comment by prathamesh-sonpatki** [comment]
https://github.com/rubyconfindia/2016/issues/1 and https://github.com/rubyconfindia/2017/issues/1 are remaining issues. Rest is working so closing this issue.
