### ISSUE TITLE
Links on the site https://2015.rubyconfindia.org/ are broken

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#121]
Example when I click on Sponsors it takes me to a blank page https://2015.rubyconfindia.org/2015/sponsor.html

**Comment by prithvi16** [comment]
@smtalimett  can you give push access to 2015 repo to me? I have fixed the links.

**Comment by smtalimett** [comment]
@prithvi16 given you push access - check and let me know.

**Comment by prithvi16** [comment]
@smtalimett  Got it. Thanks!

**Comment by prathamesh-sonpatki** [comment]
Fixed
