### ISSUE TITLE
Add Registration and CFP link on landing page

### ISSUE THREAD

**Issue by Shwetakale** [rubyconfindia/2019#124]

**Comment by prathamesh-sonpatki** [comment]
CFP link is already present: https://monosnap.com/file/4701crq1fUZO0ooWVXIEsuPNmViqY6

@prithvi16 Please add registration link in the About section at the end.

**Comment by smtalimett** [comment]
You could add a Register link like you have done for GCI19.

![rci19](https://user-images.githubusercontent.com/18298741/45666354-c7399a00-bb32-11e8-9207-bd5d511a42bf.jpg)
