### ISSUE TITLE
Please add RAVIENCE DIGITAL PVT LTD as a Hoodies and Mugs Sponsor

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#129]

**Comment by smtalimett** [comment]
![pepipost_logo](https://user-images.githubusercontent.com/18298741/46994430-0824ce80-d132-11e8-8278-1e7729181bd7.png)

**Comment by prithvi16** [comment]
@smtalim 
I searched but they don't seem to have a website. Please post the website of this company so that I can grab the about-us section and link to them on Logo.

**Comment by smtalimett** [comment]
Check this site https://pepipost.com/

**Comment by prithvi16** [comment]
Thanks, will submit PR right away.

**Comment by prithvi16** [comment]
fixed in #132 . Please let me know if there are any changes.
