### ISSUE TITLE
How are we running this site locally?

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rubyconfindia/2019#13]
Are we running locally using jekyll?

**Comment by vjdhama** [comment]
Yes. It'll be available on `localhost:4000` using `jekyll serve`.

**Comment by prathamesh-sonpatki** [comment]
Thanks.

**Comment by vjdhama** [comment]
@prathamesh-sonpatki I'm sorry. I made a mistake. The new version will run on jekyll that way. I don't know how current version will run locally.

**Comment by prathamesh-sonpatki** [comment]
Cool, feel free to close https://github.com/rubyconfindia/rubyconfindia.github.io/pull/14 if it messes with new version.

**Comment by prathamesh-sonpatki** [comment]
Ok, thanks
