### ISSUE TITLE
Add Joshsoftware as a Gold Sponsor

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#130]
Logo from old site

**Comment by prithvi16** [comment]
update: Will submit PR by tonight.

**Comment by smtalimett** [comment]
What happened?

**Comment by prithvi16** [comment]
On it right now.

**Comment by prithvi16** [comment]
fixed in #133 . Please let me know if there are any changes.

**Comment by smtalimett** [comment]
The statement The hand picked Josh Software team of 38 regularly" should be "The hand picked Josh Software team of 65 regularly"

**Comment by prithvi16** [comment]
fixed in #136 .
