### ISSUE TITLE
Add Mavenhive as Bag Sponsor 

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#151]
[NewLogo_MavenHive_2018.zip](https://github.com/rubyconfindia/rubyconfindia.github.io/files/2665469/NewLogo_MavenHive_2018.zip)

[MavenHive](http://www.mavenhive.in/) is a Bangalore based boutique consulting firm specializing in end-to-end product development and training. They have built a team of talented people from diverse backgrounds who have come together for one mission, to "turn ideas into awesome software" !

Over the last 6+ years, they have worked with several startups and organizations from across the world realize their product vision and help them achieve major milestones in their journey. MavenHive has been a long time supporter of the Ruby community in India. They are hiring polyglot, full stack devs for their fast growing team.

**Comment by prithvi16** [comment]
@smtalimett 
sorry, I could not understand what exactly needs to be posted. Do you want me to add the image in pdf or description with a logo like others?

**Comment by smtalimett** [comment]
Just the image would do.

**Comment by smtalimett** [comment]
Here's a write up for Mavenhive:

[MavenHive](http://www.mavenhive.in/) is a Bangalore based boutique consulting firm specializing in end-to-end product development and training. They have built a team of talented people from diverse backgrounds who have come together for one mission, to "turn ideas into awesome software" ! 

Over the last 6+ years, they have worked with several startups and organizations from across the world realize their product vision and help them achieve major milestones in their journey. MavenHive has been a long time supporter of the Ruby community in India. They are hiring polyglot, full stack devs for their fast growing team.


[NewLogo_MavenHive_2018.zip](https://github.com/rubyconfindia/rubyconfindia.github.io/files/2665462/NewLogo_MavenHive_2018.zip)

**Comment by prithvi16** [comment]
Taking this up
