### ISSUE TITLE
Past Conference page

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#23]
Gives 404 error

**Comment by vjdhama** [comment]
This is going to take a while. We're trying figure this out.

**Comment by coderhs** [comment]
Here are link to the previous conferences.

2014 - http://rubyconfindia.org/rci2014/
2013 - http://rubyconfindia.org/rci2013/
2012 - http://rubyconfindia.org/rci2012/
2011 - http://rubyconfindia.org/rci2011/
2010 - http://rubyconfindia.org/rci2010/

I am not sure how these links are online, but since they are following such a patters we should move the 2015 site files to this location as well.  @ajeygore do you know where the above sites are hosted, so that we could place the 2015 website as well in that location.

**Comment by vjdhama** [comment]
@coderhs I was also thinking about that. I will try to figure it out first thing tomorrow.

**Comment by ajeygore** [comment]
You can find previous conferences under Sidu's handle, and take that data
and merge it here. It will be good to have all that under one roof.

Thanks
Ajey

On Mon, Jan 11, 2016 at 8:04 PM, Vijay Dhama notifications@github.com
wrote:

> @coderhs https://github.com/coderhs I was also thinking about that. I
> will try to figure it out first thing tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rubyconfindia/rubyconfindia.github.io/issues/23#issuecomment-170569468
> .

## 

Thanks

Ajey

**Comment by prashant3863** [comment]
@ajeygore @IndianGuru Can someone please create a repo called rci2015 for the 2015 website.We don't have the acess to do that. We'll push the code there.
We are still trying to figure out how are the older websites hosted?

**Comment by prashant3863** [comment]
We think we have figured out how to make it work. We need a repo named rci2015 for that.

**Comment by IndianGuru** [comment]
@ajeygore needs to do that since I don't have enough permissions to create a new repo.

**Comment by ajeygore** [comment]
Why do you need repo named rci2015 just export from Sidu's repo and check it
in over here

**Comment by vjdhama** [comment]
@ajeygore As I previously mentioned in the mail, going forward it's be easy organize all the previous year's conference source code in their own repo's. This way we won't have to manage 2015's source code in the 2016's repo. 

Anyways I couldn't find any rubyconfindia(except a repo which is empty) related content on @kaiwren github. Can you please clarify what you meant by exporting from sidu's repo?

/cc @IndianGuru @prashant3863

**Comment by ajeygore** [comment]
Well. how do you think that you gonna link and update them? how would you put
them in sub urls? because we have single domain name

Ajey

**Comment by prashant3863** [comment]
According to what I have read so far, If we create a repo called rci2015 and then push the website in gh-pages branch then it will get hoted at `<username>.github.io/rci2015` 
I believe this is what we have done for the previous year websites as well like rci2014,13,12 and so on. just what @coderhs mentioned in this thread earlier.
Those websites are working fine.
cc @ajeygore @vjdhama @IndianGuru

**Comment by IndianGuru** [comment]
@ajeygore yes that works. Creating a repo called rci2015 will work. Give me admin rights and I'll create it.

**Comment by vjdhama** [comment]
So what happens is, if you have an organization(say rubyconfindia) the `master` branch of `<organization name>.github.io` is used to display content. But if you want the same for a project(say rci2015), the project has to use `gh-pages` to render content and `url` will be something like `rubyconfindia.org/rci2015`. The previous conference repo's are hosted on github using the same principle.

/cc @ajeygore @IndianGuru

**Comment by ajeygore** [comment]
Done, you have rights.

**Comment by IndianGuru** [comment]
Guys rci2015 repo has been created and you all have been added as Collaborators.

**Comment by vjdhama** [comment]
Thanks @IndianGuru @ajeygore.

**Comment by prashant3863** [comment]
The links to all the past conferences are live now.
