### ISSUE TITLE
Associate Sponsor Image Missing

### ISSUE THREAD

**Issue by exagil** [rubyconfindia/2019#26]
<img width="823" alt="screen shot 2016-01-11 at 4 02 22 pm" src="https://cloud.githubusercontent.com/assets/6065869/12231357/d3d19eb8-b87c-11e5-9b22-0255ff816c19.png">

**Comment by vjdhama** [comment]
Yep. That's a known issue. We don't have the appropriate content yet.

**Comment by exagil** [comment]
Have a placeholder there

**Comment by IndianGuru** [comment]
Okay. Here is it.

Please change Raftaar Technologies Pvt Ltd to Limo.

"[Limo](https://www.limoapp.in/) helps individuals, groups, communities and corporates to deploy their own or shared mass transit infrastructure. Our bespoke transport solutions help everyone to have an eco-friendly, economical, safe and comfortable journey to and from work."

![limo_logo](https://cloud.githubusercontent.com/assets/178281/12231510/2b6fadb2-b87e-11e5-91ae-30b5a20582ef.png)

**Comment by vjdhama** [comment]
@IndianGuru Ok. I'll change it.
