### ISSUE TITLE
Speaker Katrina Owen write up

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#28]
Katrina accidentally became a developer while pursuing a degree in molecular biology. When programming, her focus is on automation, workflow optimization, and refactoring. She works primarily in Go and Ruby, contributes to several open source projects, and is the creator of [exercism.io](http://exercism.io/).

**Comment by vjdhama** [comment]
I am not sure of adding this, atleast until we have writeup on other speakers too.
