### ISSUE TITLE
Add Cybrilla as an Associate Sponsor

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#38]
![logo](https://cloud.githubusercontent.com/assets/178281/12805721/6e7e8278-cb24-11e5-9bf2-5711e29d2b05.png)

An agile software development firm that builds robust, scalable and secure applications, basically applications that rock! At present, their fingers are dipped in global products for IoT in Retail, Augmented Reality in Banking, Social Networking for Celebs and a lot of Fin-tech. Their motto is to leverage technology to change lives and are always looking for more hands for their mission.

**Comment by prashant3863** [comment]
Is this their website?  http://www.cybrilla.com/
