### ISSUE TITLE
Add MavenHive Technologies Pvt Ltd as Associate Sponsors

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#42]
![mavenhive_red_01](https://cloud.githubusercontent.com/assets/178281/12911742/9105de44-cf3a-11e5-9a88-3c156b2f0d83.png)

**Comment by vjdhama** [comment]
@IndianGuru do we have description for mavenhive?

**Comment by IndianGuru** [comment]
Not yet but hopefully in a day or two.

**Comment by IndianGuru** [comment]
Their write up -

[MavenHive](http://www.mavenhive.in/) is a Bangalore based technology consulting firm founded by professionals with over a decade of experience. We work with product companies worldwide to convert their ideas into high quality software. Technology is our forte and delighting customers while being excited about our work is why we’re here. We are looking to add promising people to our team.

**Comment by IndianGuru** [comment]
Can we add this today. We have received their sponsorship money.

**Comment by vjdhama** [comment]
@IndianGuru I will finish this up today.

**Comment by vjdhama** [comment]
@IndianGuru this won't fix today since the image does not have transparent background. I'll try to fix this first thing in the morning.

**Comment by IndianGuru** [comment]
They have sent 3 logos. Sent it to you by email.

**Comment by vjdhama** [comment]
@IndianGuru Added mavenhive to associate sponsors. Fixed in https://github.com/rubyconfindia/rubyconfindia.github.io/commit/f97de303e07996ee670bfe10b763d93e1c769bd5.
