### ISSUE TITLE
Add DigitalOcean as Gold Sponsor

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#43]
![digital-ocean](https://cloud.githubusercontent.com/assets/178281/12937497/444d2fd6-cfcf-11e5-9d8d-51debcf1de52.png)

[DigitalOcean](https://www.digitalocean.com/) is the world’s fastest growing cloud hosting provider built for developers. Our mission is simple: we’re passionate about making complex infrastructure simple and delighting our customers with a seamless experience that brings them joy. New users can easily deploy a blazing fast cloud server in 55 seconds with an intuitive control panel interface, which can be replicated on a larger scale with the company’s straightforward API.

**Comment by IndianGuru** [comment]
DigitalOcean is a Gold Sponsor not Digital Sponsor - please correct

**Comment by vjdhama** [comment]
Sry my bad.
