### ISSUE TITLE
Add Speakers Anuja Ware and Shweta Kale

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#50]
Anuja Ware: Anuja lives in Pune, India. She is a programmer at Josh Software. She works in ROR and also trying to become an good opensource contributor. She enjoys signing and sports in her free time.

![anuja](https://cloud.githubusercontent.com/assets/178281/13246664/02ce361a-da3b-11e5-99d8-f5370a6532ee.jpg)

Shweta Kale: Shweta lives in Pune, India. She is associated with Josh Software since July 2014 as a software developer. She is an enthusiastic programmer and an avid open source contributor. When free she likes to go for trekking and also spends some quality time with her family and friends.

![shweta](https://cloud.githubusercontent.com/assets/178281/13246675/0e52d522-da3b-11e5-832d-3f3dbf82f7ee.JPG)

**Comment by vjdhama** [comment]
@IndianGuru Do we also have twitter profile links?

**Comment by IndianGuru** [comment]
Twitter: @anujaware and @Shwetakale13
