### ISSUE TITLE
Add Speaker Manohar Amrutkar

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#52]
Manohar is a programmer, traveller and he wants to become a data scientist. He started career in programming using Rails and became Ruby enthu. Currently working as full stack developer using AngularJS and Rails. Data and stats thrills him so he started diving into big data related technologies.

![manohar](https://cloud.githubusercontent.com/assets/178281/13276138/275617e4-dae2-11e5-9948-2da3741967f4.jpg)

Twitter @_manoharaa

**Comment by vjdhama** [comment]
@IndianGuru Twitter ID?

**Comment by IndianGuru** [comment]
Twitter: @_manoharaa
