### ISSUE TITLE
Add BigBinary as Associate Sponsor

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#62]
Logo - https://files.slack.com/files-pri/T04BUMHMZ-F0R5XNZCY/logo_blue.png

BigBinary is a Ruby on Rails Consulting company based in San Francisco  and Miami. They build web and mobile applications using Ruby on Rails and React Native.

**Comment by vjdhama** [comment]
@IndianGuru Can't access slack. Not invited?

**Comment by IndianGuru** [comment]
![logo_blue](https://cloud.githubusercontent.com/assets/178281/13628633/a6906bf0-e5f9-11e5-98e0-4d240383c9d8.png)
