### ISSUE TITLE
Update a page on site

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#73]
Please update the following page http://rubyconfindia.org/travelling-to-kochi/ with contents from http://krug.github.io/rubyconfindia/kochi ?

**Comment by prathamesh-sonpatki** [comment]
@nithinbekal Can you send PR

**Comment by nithinbekal** [comment]
@prathamesh-sonpatki Sure. I'll update it tonight.

**Comment by prathamesh-sonpatki** [comment]
http://rubyconfindia.org/travelling-to-kochi/ looks good, thanks @nithinbekal
