### ISSUE TITLE
RCI17 Speaker | Talk Title | Talk details - can we have a page for this asap?

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#75]

**Comment by smtalimett** [comment]
http://rubyconfindia.org/program/

**Comment by prathamesh-sonpatki** [comment]
Yup, I will take care of this in a day or two.

**Comment by smtalimett** [comment]
The file https://github.com/rubyconfindia/rubyconfindia.github.io/blob/master/rci-program/index.html gives an error saying not UTF-8. 
The file index.html -

---
layout: page
title: RCI Program
---


{% include pages/rci_program_index.html %}

The rci_program_index.html file is here -https://github.com/rubyconfindia/rubyconfindia.github.io/blob/master/_includes/pages/rci_program_index.html

**Comment by smtalimett** [comment]
Can we make it live today?

**Comment by prathamesh-sonpatki** [comment]
Need to add rest of the details.

http://rubyconfindia.org/program/

**Comment by smtalimett** [comment]
shall do so in some time

**Comment by smtalimett** [comment]
Completed

**Comment by prathamesh-sonpatki** [comment]
Looking good :+1:

We should similar for GCI?

**Comment by smtalimett** [comment]
Yes.
