### ISSUE TITLE
Add RedPanthers as "Speaker Sponsor"

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#77]

**Comment by prathamesh-sonpatki** [comment]
@smtalim I will get the logo from the old site, please post writeup.

**Comment by smtalimett** [comment]
Red Panthers is a Ruby on Rails development studio, based in the beautiful city of Cochin (known as the queen of Arabian Sea), India. We work with our client in hand-crafting applications that turn their ideas into profitable and effective businesses. Over the years we have worked with clients ranging from single-person startup to MNC that have over 10,000 employees. Got a business/idea in your hand? Do you lack technological support? Unsure about how to implement your ideas? We, Red panthers, is here to help you materialize your ideas.
