### ISSUE TITLE
Add Zach Holman as keynote speaker

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [rubyconfindia/2019#89]
Bio and photo: https://zachholman.com/bio

**Comment by smtalimett** [comment]
Zach does not appear on website

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki Looks like you have commented this out. When do we want to announce Zach as a keynote speaker?

**Comment by prathamesh-sonpatki** [comment]
Yes, I had commented out before announcing Avdi as keynote speaker. @anuja-joshi Please uncomment before announcing.
