### ISSUE TITLE
Sponsors need to be upgraded

### ISSUE THREAD

**Issue by IndianGuru** [rubyconfindia/2019#9]
Sponsors - please update the sponsor list.

Confirmed Sponsors -

Silver Sponsor - Chillr.in (logo attached) - payment received
Media Sponsor - Red Panthers - payment is being made on 1st Dec.
Associate Sponsor - RBus - have sent them our invoice

Have verbally said yes -
Gold - JoshSoftware and Qwinix
Silver - Smartzip

**Comment by vjdhama** [comment]
I don't have any details on associate sponsor Raftaar Technologies Pvt Ltd. They don't have any site.

**Comment by IndianGuru** [comment]
Raftaar is a new startup - no site yet. Have emailed the founder for details.
