### ISSUE TITLE
Add Amuratech as Silver Sponsor

### ISSUE THREAD

**Issue by smtalimett** [rubyconfindia/2019#99]

**Comment by smtalimett** [comment]
of RCI18

**Comment by prathamesh-sonpatki** [comment]
@Shwetakale Use logo and bio from Deccan Ruby site.

**Comment by Shwetakale** [comment]
@prathamesh-sonpatki We didn't have bio on Deccan Ruby Site. I am taking bio from RubyConf India 2017. We can change it later if required.
